config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  get 'home/index'
  root to: 'home#index'
  get 'post/new'
  get 'user/settings'
  get 'roles', to: 'user#roles'
  get 'users/all', to: 'user#users'
  post 'post/new', to: 'post#create'
  get 'file/:id/:file_name', to: 'file#get'
  get 'files/:id/download', to: 'file#download_all_files'
  get 'post/:id', to: 'post#get'
  get 'user/:id', to: 'user#get'
  get 'files/:id', to: 'file#get_all'
  get 'files/:id/gallery', to: 'file#get_all_image'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    admin if user.role? :admin
    user(user)
  end

  private def user(me)
    can :create, Post
    can :manage, me
    can :delete, me.posts # why it don't work?
  end

  private def admin
    can :manage, User.all
    can :change, Role
    can :manage, Post.all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :description, presence: true
  belongs_to :user

end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  has_many :posts
  before_validation :set_default_role
  validates_with UserValidator

  def role?(role_sym)
    role.name.underscore.to_sym == role_sym
  end

  def ability
    Ability.new(self)
  end

  def active_for_authentication?
    super && active
  end

  private

  def set_default_role
    self.role = Role.find_by_name('user') if role.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/file_controller.rb
class FileController < ApplicationController
  before_action :authenticate_user!

  def get
    outcome = FindFile.run(params.permit(:id, :file_name))
    if outcome.valid?
      send_data(outcome.file.read, filename: outcome.file_name_with_type)
    else
      respond_to do |format|
        format.html {render body: '', status: 422, content_type: 'text/html'}
        format.json {render json: outcome.errors.messages, status: 422}
      end
    end
  end

  def get_all
    outcome = FindFiles.run(params.permit(:id))
    if outcome.valid?
      render json: outcome.files_name
    else
      render json: outcome.errors.messages, status: 422
    end
  end

  def get_all_image
    outcome = FindGalleryFiles.run(params.permit(:id))
    if outcome.valid?
      render json: outcome.files_name
    else
      render json: outcome.errors.messages, status: 422
    end
  end

  def download_all_files
    outcome = CreateZipFiles.run(params.permit(:id))
    if outcome.valid?
      send_data(outcome.zip_stream.read, filename: outcome.zip_name)
    else
      respond_to do |format|
        format.html {render body: '', status: 422, content_type: 'text/html'}
        format.json {render json: outcome.errors.messages, status: 422}
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.all
    @post.each do |id|
      id.thumbnail
    end
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def get
    outcome = FindPost.run(params)
    if outcome.valid?
      respond_to do |format|
        @post = outcome.result
        format.html {
          render :get
        }
        format.json {
          render json: @post
        }
      end
    else
      respond_to do |format|
        format.html {
          render body: '', status: 422, content_type: 'text/html'
        }
        format.json {
          render json: outcome.errors.messages, status: 422
        }
      end
    end
  end

  def create
    outcome = CreatePost.run(params.require(:post).merge(user_id: current_user.id))
    if outcome.valid?
      redirect_to root_path
    else
      flash[:alert] = ResourcesMessage.new(:create_post, outcome.errors).message
      redirect_to post_new_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  prepend_before_action :require_no_authentication, only: [:cancel]
  prepend_before_action :authenticate_scope!, only: [:edit, :update, :destroy, :new, :create]


  def update
    update_services = UpdateServices.new(self)
    if current_user.ability.can? :change, Role
      update_services.change_role(account_update_params_role)
    else
      update_services.update_with_password(resource, account_update_params)
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params_role
    params.require(:user).permit(:email, :role_id)
  end

  def sign_up(resource_name, resource)
    nil
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  before_action AdminFilter, except: :get


  def roles
    render json: Role.all
  end

  def users
    render json: User.all
  end

  def get
    outcome = FindUser.run(params.merge(user: current_user))
    if outcome.valid?
      render json: outcome.result
    else
      render json: outcome.errors.messages, status: 422
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # @return [Configuration]
  def config
    Configuration.instance
  end

  def is_active(path)
    if request.path == path
      'active'
    else
      ''
    end
  end

  def stylesheet_tag(controller)
    with_out_controller = %w(devise/sessions devise/passwords)
    render = true
    with_out_controller.each do |with_out|
      render = false if controller == with_out
    end
    stylesheet_link_tag controller if render
  end

end

app/helpers/configuration.rb
class Configuration
  attr_reader :server_path, :image_format

  def initialize
    @server_path = "#{Rails.root}/server/ftp/"
    @image_format = /.raw|.png|.jpg/
  end

  @@instance = Configuration.new

  def self.instance
    @@instance
  end

  private_class_method :new
end

app/helpers/home_helper.rb
module HomeHelper
  def get_thumbnail(post)
    root_url+"file/#{post.id}/#{post.thumbnail}"
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper

end

app/views/home/index.slim
h1 <small>Ostatnio dodane</small>
hr
- @post.each do |post|
  div
    h2 = post.title
    h5 <span class="glyphicon glyphicon-time"></span> Dodany przez #{post.user.first_name} #{post.user.last_name}, #{post.created_at}
    h5 <span class="label label-info">#{post.tag}</span>
    div class="row" onClick="go_to_post(#{post.id})"
      div class="col-sm-3"
        img class="img-thumbnail" src="#{get_thumbnail(post)}" onerror='this.src="notfound.jpg"'
      div class="col-sm-8"
        p
          = post.description
  hr

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchoolArchives</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://unpkg.com/vue"></script>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_tag(params[:controller]) %>
  <%= csrf_meta_tags %>

</head>

<body>
<div class="container-fluid">
  <% if user_signed_in? %>
      <div class="row content">
        <div class="col-sm-2 sidenav">
          <h4>Archiwum szkoły</h4>
          <ul class="nav nav-pills nav-stacked">
            <li class="<%= is_active(root_path) %>"><%= link_to("Lista postow", root_path, method: :get) %></li>
            <li class="<%= is_active(post_new_path) %>"><%= link_to("Nowy post", post_new_path, method: :get) %></li>
            <% if current_user.role.id == Role.find_by_name("admin").id %>
                <li>
                  <a class="dropdown-toggle" type="button" id="menu-admin" data-toggle="dropdown">Panel administracyjny</a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="menu-admin">
                    <li role="presentation <%= is_active(user_settings_path) %>"><%= link_to("Menadżer ról", user_settings_path, method: :get) %>
                    <li role="presentation <%= is_active(new_user_registration_path) %>"><%= link_to("Tworzenie konta", new_user_registration_path, method: :get) %></li>
                  </ul>
                </li>
            <% end %>
            <li><%= link_to("Wyloguj się", destroy_user_session_path, method: :delete) %></li>
          </ul>
          <br>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Wpisz tag..">
            <span class="input-group-btn">
          <button class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
          </div>
        </div>

        <div class="col-sm-10">
          <%= yield %>
        </div>
      </div>

      </div>

      <footer class="container-fluid">
        <p></p>
      </footer>
  <% else %>
      <div class="content">
        <%= yield %>
      </div>
  <% end %>


  </body>
<%= javascript_include_tag 'application' %>
</html>

app/views/post/get.html.slim
= react_component('GetPage',{id_post: @post.id})

app/views/post/new.slim
h1 <small>Nowy post</small>
hr
  - if alert
    div class="alert alert-danger"
      = alert

  = form_for @post, :url => post_new_path, :multipart => true do |f|
    div class="form-horizontal"
      div class="form-group"
        = f.label :title, 'Tytuł', :class => 'control-label col-sm-1'
        div class="col-sm-11"
          = f.text_field :title, :class => 'form-control', :placeholder => 'Tytuł'
      div class="form-group"
        = f.label :description, 'Opis', :class => 'control-label col-sm-1'
        div class="col-sm-11"
          = f.text_area :description, :rows => 4, :cols => 50, :class => 'form-control', :placeholder => 'Opis'
      div class="form-group"
        = f.label :tag, :class => 'control-label col-sm-1'
        div class="col-sm-11"
          = f.text_field :tag, :class => 'form-control', :placeholder => '#ezn'
      div class="form-group"
        div class="col-sm-offset-1 col-sm-10"
          = f.file_field :files, :multiple => true, :class => 'btn btn-primary'
      div class="form-group"
        div class="col-sm-offset-1 col-sm-10"
          = f.submit 'Wyślij', :class => 'btn btn-default'

app/views/user/settings.erb
<!--<ul id="app">-->
<!--<li v-for="item in items">-->
<!--{{ item.message}}-->
<!--</li>-->
<!--</ul>-->
<table id="role" class="table">
  <tr>
    <th>Imie</th>
    <th>Nazwisko</th>
    <th>Rola</th>
    <th></th>
  </tr>
  <tr v-for="user in users">
    <td>
      {{user.first_name}}
    </td>
    <td>
      {{user.last_name}}
    </td>
    <td>
      {{get_user_role(user.role_id)}}
      <ul class="list-group" v-bind:class="{ active: !row_is_active(user) }">
        <li class="list-group-item" v-for="role in roles" v-bind:class="{ select: selected_role[role.id-1].isSelected }" v-on:click="select_role(role.id)">{{role.name}}</li>
      </ul>
    </td>
    <td>
      <button type="button" class="btn-danger btn" v-on:click="show_list(user)" v-bind:class="{ active: row_is_active(user) }">Zmień</button>
      <button type="button" class="btn-success btn" v-on:click="save_change(user)" v-bind:class="{ active: !row_is_active(user) }">Zapisz</button>
    </td>
  </tr>
</table>